Changes to component 'EventosTimeline'
recepcaoimeusp/site pull request #59
Opened 2024-01-28 01:52 UTC by giovannauchoagomes

### New design and animation for the 'EventosTimeline' component:
- Modified the timeline's line color.
- The timeline's dot is now a 'lantern' with 'on' and 'off' animations.
- Added a new icon at the end of the timeline.
- Changed text color.

2024-01-28 21:05 UTC, josemayer requested changes

2024-01-28 21:05 UTC, josemayer commented on components/EventosTimeline.vue
> +  filter: drop-shadow(0 0 0.75rem white);
Talvez a luz fique muito concentrada com esse blur-radius, seria interessante aumentar um pouco.
```suggestion
  filter: drop-shadow(0 0 1rem white);
```

2024-01-28 21:35 UTC, giovannauchoagomes commented on components/EventosTimeline.vue
> +  filter: drop-shadow(0 0 0.75rem white);
Melhora mesmo!

2024-01-29 16:05 UTC, josemayer approved these changes
Muito bom!!

2024-01-29 16:06 UTC, merged